### ISSUE TITLE
Stacktraces

### ISSUE THREAD

**Issue by felixsanz** [snorpey/triangulate-image#23] opened 2016-06-21 23:19 UTC
In Node, this example:

``` javascript
var fs = require('fs');
var triangulate = require('triangulate-image')

fs.readFile( './1.jpg', function ( err, buffer ) {
    if ( err ) { throw err; }

    triangulate()
        .fromBuffer( buffer )
        .toSVG()
        .then( function ( svgMarkup ) {
            fs.writeFile( './1.svg', svgMarkup, function ( err ) {
                if ( err ) { throw err; }
                console.log( 'created an svg file.' );
            } );
        } );
} );
```

Produces this:

```
<--- Last few GCs --->

    9120 ms: Mark-sweep 1227.7 (1266.6) -> 1019.2 (1058.3) MB, 130.3 / 0 ms (+ 0.2 ms in 2 steps since start of marking, biggest step 0.1 ms) [allocation failure] [GC in old space requested].
    9233 ms: Mark-sweep 1019.2 (1058.3) -> 1019.2 (1058.3) MB, 113.3 / 0 ms [allocation failure] [GC in old space requested].
    9347 ms: Mark-sweep 1019.2 (1058.3) -> 1019.2 (1058.3) MB, 113.8 / 0 ms [last resort gc].
    9461 ms: Mark-sweep 1019.2 (1058.3) -> 1019.2 (1058.3) MB, 114.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3ce3bb5c9e59 <JS Object>
    1: new constructor(aka Sobel) [/home/felixsanz/Desktop/triang/node_modules/sobel/sobel.js:~4] [pc=0x2ca63df83214] (this=0x2d0d58404531 <a Sobel with map 0x25ee39f279e9>,imageData=0x3ce3bb504189 <undefined>)
    3: Sobel(aka Sobel) [/home/felixsanz/Desktop/triang/node_modules/sobel/sobel.js:~4] [pc=0x2ca63df71031] (this=0x3ce3bb504189 <undefined>,imageData=0x2d0d58436691 <an Ob...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
fish: “node test.js” terminated by signal SIGABRT (Abort)
```

So the lib doesn't work at all

**Comment by snorpey** [comment] 2016-06-23 12:46
Hey @felixsanz,

thank you for reporting this issue. For some reason, I can't seem to reproduce it on my machine.

Could you provide me with some information about the environment that you were trying to run the script in? That would make it much easier for me to debug the issue.
- Which operating system are you using?
- Could you provide the source image that you were trying to process?
- Does the library work if you try to triangulate other source images or does it fail every time?
- Which version of node were you using?

Thanks again!

**Comment by felixsanz** [comment] 2016-06-23 14:33
I'm running Arch Linux with node 6.2.2. The image was from https://unsplash.com/, any of those produce the same result, so pick your favorite or [this](https://images.unsplash.com/photo-1465205568425-23fdd3805e49?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&s=7e476dbc9096ec1c869bd2cb97d82c70).

The triangulate lib doesn't work no matter what i try.

Maybe those images are too big? But online in your playground works :/

**Comment by snorpey** [comment] 2016-06-29 19:51
@felixsanz Thank you for the quick reply. I currently don't have access to an Arch Linux box so I have a hard time debugging the issue.

Is it possible that there's an issue with [node-canvas](https://github.com/Automattic/node-canvas) on your platform? The node-canvas library is only used in the node part of the code. I don't have any evidence for this assumption, so I might be wrong...

Without more information, I'm not really sure how to fix this issue, sorry :-/

**Comment by felixsanz** [comment] 2016-06-29 20:21
I  also tried node-canvas and, at least the examples from their repo, it works without any problem :/

I wish i could provide more details...

**Comment by snorpey** [comment] 2016-07-04 09:16
thank you for testing this out, good to know.

i'll probably revisit this issue some time later when i have a little bit more time on my hands...

in the meantime, could you let me know what happens if you install the dev dependencies and run the tests (which tests fail & what the output is etc...)?

i'm sorry that can't be more helpful here, i just don't have any clue what might be causing this bug... 

thanks again for your time & effort reporting this bug!

**Comment by felixsanz** [comment] 2016-07-06 20:05
Sorry for delay. I cloned this repo and run the tests. No errors, everything worked fine.

I then created a js file in the root of the repo with this contents:

``` javascript
var fs = require('fs');
var triangulate = require('./dist-node')

fs.readFile( './1.jpg', function ( err, buffer ) {
    if ( err ) { throw err; }

    triangulate()
        .fromBuffer( buffer )
        .toSVG()
        .then( function ( svgMarkup ) {
            fs.writeFile( './1.svg', svgMarkup, function ( err ) {
                if ( err ) { throw err; }
                console.log( 'created an svg file.' );
            } );
        } );
} );
```

Notice that i'm now using `./dist-node/index.js`. And run it.

Result? The same:

> node index.js 

```
<--- Last few GCs --->

    8777 ms: Mark-sweep 1227.3 (1265.6) -> 1019.1 (1057.3) MB, 160.6 / 0 ms [allocation failure] [GC in old space requested].
    8942 ms: Mark-sweep 1019.1 (1057.3) -> 1019.1 (1057.3) MB, 165.4 / 0 ms [allocation failure] [GC in old space requested].
    9093 ms: Mark-sweep 1019.1 (1057.3) -> 1019.1 (1057.3) MB, 150.7 / 0 ms [last resort gc].
    9242 ms: Mark-sweep 1019.1 (1057.3) -> 1019.1 (1057.3) MB, 149.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2450022c9e59 <JS Object>
    1: new constructor(aka Sobel) [/home/felixsanz/Desktop/trian/node_modules/sobel/sobel.js:~4] [pc=0xaf6d7e7f2cd] (this=0x253256108979 <a Sobel with map 0x3277d9265f9>,imageData=0x245002204189 <undefined>)
    3: Sobel(aka Sobel) [/home/felixsanz/Desktop/trian/node_modules/sobel/sobel.js:~4] [pc=0xaf6d7e70bb1] (this=0x245002204189 <undefined>,imageData=0x253256108411 <an Object with map 0x327...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
fish: “node index.js” terminated by signal SIGABRT (Abort)
```

If i change my 1.jpg and use your example.png (Lilcoln), it works.

So... that `JavaScript heap out of memory` is clearly what happens. Something in your library is using too much memory to process my image. Resizing the image to a lower resolution fix the problem. This will be harder to debug, maybe impossible and maybe not worth it, but i leave it up to you :P

**Comment by felixsanz** [comment] 2016-07-06 20:06
You can close the issue if you want!

**Comment by snorpey** [comment] 2016-07-07 07:30
hey @felixsanz thanks again for your efforts and for investigating this issue!
i'll definitely look into this issue some more once i have a little more time on my hands...

**Comment by snorpey** [comment] 2017-06-02 19:54
still can't reproduce this issue on any of my machines... i'm closing the issue for now. sorry for not being able to help more, and thanks again for using the library…

**Closed as completed by snorpey** 2017-06-02 19:54 UTC
Labels: bug
